// Balance tuning knobs. Source of truth: docs/04-BALANCE.md.
// Change here, re-run balance sims before release.

export const BALANCE = {
  COST_MULTIPLIER: 1.15,
  DREAD_MULT_PER_UNIT: 0.1,
  ASCEND_THRESHOLD: 1e6,
  DREAD_GAIN_DIVISOR: 1e6,
  DREAD_GAIN_COEF: 2,

  OFFLINE_EFFICIENCY: 0.5,
  OFFLINE_CAP_HOURS: 4,
  OFFLINE_CAP_HOURS_REWARDED: 6,
  OFFLINE_CAP_HOURS_METHUSELAH: 6,
  OFFLINE_CAP_HOURS_METHUSELAH_REWARDED: 8,

  BASE_CLICK_POWER: 1,
  CLICK_SCALING_RATIO: 0.0015,
  CRIT_CHANCE: 0.08,
  CRIT_MULTIPLIER: 5,
  CRIT_CHANCE_FRENZY: 0.24,

  BOOST_DURATION_SEC: 15,
  BOOST_COOLDOWN_SEC: 60,
  BOOST_COOLDOWN_SEC_LORD_OF_NIGHT: 30,
  BOOST_DURATION_REWARDED_SEC: 120,
  BOOST_MULTIPLIER: 2,
  FRENZY_DURATION_SEC: 30,

  AUTO_CLAIM_INTERVAL_SEC: 5,
  DAILY_BOOST_CHARGES: 3,
  GLOBAL_MULT_BONUS_PROGENITOR: 1.5,

  UNLOCK_THRESHOLD_RATIO: 0.3,

  FORM_THRESHOLDS: {
    ELDER: 1,
    LORD_OF_NIGHT: 3,
    METHUSELAH: 7,
    PROGENITOR: 15,
    TERA_OVERLORD: 30,
    HORROR_INCARNATE: 50,
    THIRST: 100,
  },
} as const;
