// Phase L — unique Thrall roster.
//
// These are COLLECTIBLE characters (not generators). The generators are
// now called "Servants" (see servants.ts). Each Thrall has a rarity,
// an archetype, flavour lore, and a primary bonus effect that will wire
// to the ModifierRegistry once Phase L equip logic lands.
//
// v1.0 ships 7 hero-tier thralls generated by Kenny (Rare+ only). The
// 6 common-tier thralls promised by the design doc are assets-pending
// and will fill in the roster over v1.1. Silhouettes in the UI hold
// their slots visually — the "Collected: 7/12" reads cleanly.

export type ThrallId =
  | 'ashen-vale'
  | 'blood-countess'
  | 'crimson-reaper'
  | 'lord-of-night'
  | 'mirella'
  | 'nox-the-hunger'
  | 'velmor-the-dread';

export type ThrallRarity = 'common' | 'rare' | 'epic' | 'legendary';

/** Mechanical role. Used for filter tabs and card accent. */
export type ThrallArchetype =
  | 'harvester' // blood generation
  | 'nocturne' // offline gains
  | 'predator' // active / tap gains
  | 'hybrid'; // mixed

export interface Thrall {
  readonly id: ThrallId;
  readonly name: string;
  readonly rarity: ThrallRarity;
  readonly archetype: ThrallArchetype;
  readonly lore: string;
  readonly portraitPath: string;
  /** v1.0 data-only — the bonus will wire through ModifierRegistry in
   * the next L-tickets. `value` is a multiplier (1.25 = +25%). */
  readonly primaryEffect: {
    type: 'blood_gen' | 'offline_gain' | 'active_gain' | 'tap_mult' | 'hybrid';
    value: number;
  };
}

export const THRALL_ROSTER_TARGET = 12;

export const THRALLS: readonly Thrall[] = [
  {
    id: 'nox-the-hunger',
    name: 'Nox the Hunger',
    rarity: 'rare',
    archetype: 'harvester',
    lore: 'She feeds not on blood but on memory of blood — and grows fat where others starve.',
    portraitPath: '/assets/thralls/nox-the-hunger.webp',
    primaryEffect: { type: 'blood_gen', value: 1.25 },
  },
  {
    id: 'ashen-vale',
    name: 'Ashen Vale',
    rarity: 'rare',
    archetype: 'hybrid',
    lore: 'Twice buried, thrice returned. The ash on his shoulders is from his own pyre.',
    portraitPath: '/assets/thralls/ashen-vale.webp',
    primaryEffect: { type: 'hybrid', value: 1.15 },
  },
  {
    id: 'mirella',
    name: 'Mirella, Thorn of the Court',
    rarity: 'epic',
    archetype: 'harvester',
    lore: 'A courtier with no court left. She smiles like a wound remembering.',
    portraitPath: '/assets/thralls/mirella.webp',
    primaryEffect: { type: 'blood_gen', value: 1.6 },
  },
  {
    id: 'velmor-the-dread',
    name: 'Velmor the Dread',
    rarity: 'epic',
    archetype: 'nocturne',
    lore: 'Sleeps an age between breaths. Even his absence collects interest.',
    portraitPath: '/assets/thralls/velmor-the-dread.webp',
    primaryEffect: { type: 'offline_gain', value: 1.8 },
  },
  {
    id: 'lord-of-night',
    name: 'Lord of Night',
    rarity: 'legendary',
    archetype: 'harvester',
    lore: 'He does not serve you. He merely recognises, for now, the shape of your hunger.',
    portraitPath: '/assets/thralls/lord-of-night.webp',
    primaryEffect: { type: 'blood_gen', value: 2.0 },
  },
  {
    id: 'blood-countess',
    name: 'Blood Countess',
    rarity: 'legendary',
    archetype: 'nocturne',
    lore: 'Her mirror drinks faster than she does. She has not seen herself in four hundred years.',
    portraitPath: '/assets/thralls/blood-countess.webp',
    primaryEffect: { type: 'offline_gain', value: 2.0 },
  },
  {
    id: 'crimson-reaper',
    name: 'Crimson Reaper',
    rarity: 'legendary',
    archetype: 'predator',
    lore: 'Where she walks, the clocks stutter and the dogs go quiet. She is not hunting — she is arriving.',
    portraitPath: '/assets/thralls/crimson-reaper.webp',
    primaryEffect: { type: 'active_gain', value: 1.8 },
  },
];

export const THRALLS_BY_ID: Readonly<Record<ThrallId, Thrall>> = Object.freeze(
  THRALLS.reduce(
    (acc, t) => {
      acc[t.id] = t;
      return acc;
    },
    {} as Record<ThrallId, Thrall>,
  ),
);

/** Lowercase label used in the filter tabs + card corner. */
export function archetypeLabel(a: ThrallArchetype): string {
  switch (a) {
    case 'harvester':
      return 'harvester';
    case 'nocturne':
      return 'nocturne';
    case 'predator':
      return 'predator';
    case 'hybrid':
      return 'hybrid';
  }
}

/** Rarity rank for sorting. Higher = rarer. */
export function rarityRank(r: ThrallRarity): number {
  switch (r) {
    case 'common':
      return 0;
    case 'rare':
      return 1;
    case 'epic':
      return 2;
    case 'legendary':
      return 3;
  }
}
